# Generated by Django 4.2.6 on 2023-10-28 17:56

import banking.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveIntegerField(unique=True, validators=[banking.validators.validate_account_number])),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bvn', models.PositiveIntegerField(unique=True, validators=[banking.validators.validate_bvn])),
                ('is_activated', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('clothing', 'CLOTHING'), ('food', 'FOOD'), ('health care', 'HEALTH CARE'), ('hobbies', 'HOBBIES'), ('housing', 'HOUSING'), ('loan', 'LOAN'), ('subscription', 'SUBSCRIPTION'), ('transportation', 'TRANSPORTATION'), ('utilities', 'UTILITIES'), ('other', 'OTHER')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=30)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='banking.bankaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='banking.bankaccount')),
            ],
        ),
    ]
